language: ruby
cache: bundler

rvm:
  - 2.7.1
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.5.0
install:
  - bundle config set without 'debugger'
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake quanty
  - bundle exec ruby test/suite.rb

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
# some unit tests behave differently with other
env:
  - de_CH.UTF-8 LANGUAGE=de_CH
