language: ruby
cache: bundler
sudo: false
bundler_args: --without debugger
rvm:
  - 2.4.4
  - 2.5.0
  - ruby-head
  
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4.4

script:
  - bundle exec rake quanty
  - bundle exec ruby test/suite.rb
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
# some unit tests behave differently with other
env:
  - de_CH.UTF-8 LANGUAGE=de_CH
