language: ruby
cache: bundler
sudo: required
bundler_args: --without debugger
rvm:
  - 1.9.3
script:
  - bundle exec rake quanty
  - bundle exec ruby test/suite.rb
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs