language: ruby
bundler_args: --without debugger
rvm:
  - 1.9.3
script:
  - rake quanty
  - bundle exec ruby test/suite.rb
  - rake docs
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
