language: ruby
rvm:
  - 1.9.3
script: 
  - ruby test/suite.rb 2>&1 | tee suite.log
  - rake docs
  - grep assertions, suite.log
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - zdavatz@ywesee.com
    
