services:
  oddb:
    build: .
    command: rackup --host 0.0.0.0 -p 8012
    working_dir: /code
    ports:
      - "8012:8012"
    volumes:
      - .:/code
    links:
      - postgres
  postgres:
    image: postgres:11-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oddb
      POSTGRES_DB: oddb
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  logvolume01: {}
