# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
  # see https://github.com/ruby/setup-ruby
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.0', 3.1]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Replace helveticy by sans-serif
      run: |
            echo '<?xml version="1.0"?>'  > ~/.fonts.conf
            echo '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">'  >> ~/.fonts.conf
            echo '<fontconfig>'  >> ~/.fonts.conf
            echo '<!-- Helvetica is a non true type font, and will look bad. This'  >> ~/.fonts.conf
            echo 'replaces it with whatever is the default sans-serif font -->'  >> ~/.fonts.conf
            echo '<match target="pattern" name="family" >'  >> ~/.fonts.conf
            echo '<test name="family" qual="any" >'  >> ~/.fonts.conf
            echo '<string>Helvetica</string>'  >> ~/.fonts.conf
            echo '</test>'  >> ~/.fonts.conf
            echo '<edit mode="assign" name="family" >'  >> ~/.fonts.conf
            echo '<string>sans-serif</string>'  >> ~/.fonts.conf
            echo '</edit>'  >> ~/.fonts.conf
            echo '</match>'  >> ~/.fonts.conf
            echo '<dir>~/.fonts</dir>'  >> ~/.fonts.conf
            echo '</fontconfig>'  >> ~/.fonts.conf
            fc-list

    - name: Run tests via test/suite.rb
      run: bundle exec ruby test/suite.rb

    - name: Run spec tests for compositions
      run: bundle exec rspec spec/parslet_spec.rb
